runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/corona-dashboard-ui/index.html
  upload: dist/corona-dashboard-ui/index.html
- url: /
  static_dir: dist/corona-dashboard-ui