runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/corona-dashboard-ui/\1
  upload: dist/(.*)(|\.map)

- url: /(.*)
  static_files: dist/corona-dashboard-ui/index.html
  upload: dist/corona-dashboard-ui/index.html